name: Print Message on Develop Branch Push

on:
  push:
    branches:
      - develop

jobs:
  print-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a simple text
        run: echo "Code has been pushed to the develop branch!"
